export * from './ComentarioUpdateDTO'
export * from './ManutencaoUpdateDTO'
export * from './MobilidadeUpdateDTO'
export * from './MotoristaUpdateDTO'
export * from './NoticiaUpdateDTO'
export * from './ProfissionalUpdateDTO'
export * from './UsuarioUpdateDTO'
export * from './VeiculoUpdateDTO'
